//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingManagerTrial
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAccount
    {
        public decimal userAccount1 { get; set; }
        public string Name { get; set; }
        public string DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Mother_name { get; set; }
        public string Father_name { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Date { get; set; }
        public string secret_answer { get; set; }
    }
}
